### ISSUE TITLE
Launch something on quit

### ISSUE THREAD

**Issue by ybilik** [glatigny/guipro#11]
Hi,

I would like to know if the &lt;quit&gt; node can handle an "exe" attribute so some actions can be done at PortAL shutdown. For example, it should be useful to be able to launch EjectUSB.exe, a little executable that prepares the USB key for removal.
Any way to do it with the current PortAL release ?

NB: maybe it could be implemented the same way some programs can be launched at startup, with sth like: &lt;app name="..." exe="..." **autoexit="yes"** /&gt;
or, to avoid mixed use of autorun and autoexit, create a new attribute:
&lt;app name="..." exe="..." **run="normal|startup|exit"** /&gt;

**Comment by obsidev** [comment]
Hi,

The way I used is the multiple-hotkey.
Because you can have several application using the same hotkey ; you can launch them all in the same time.
But I admit that it is not a perfect solution ; specially when you are not using an hotkey to quit.

I like the idea of a parameter which will group several states.
If we go further, we could see to add other "events", like the "lock" of the computer (and unlock) or maybe else (that I'm not thinking for the moment).

Something like:

``` XML
<!-- launch the application for a lot of events -->
<app name="..." exe="..." events="start,exit,lock,unlock" />
```

About the separator, I guess that I could manage several.
I like the pipe but it makes the text more difficult to read (so I should authorize blank spaces around).

Kind regards,
J

**Comment by ybilik** [comment]
Yes, the shortcut will not run with mouse actions.

In my example, I use a pipe only to list the possible values. In my mind, the "run" attribute could only hold one value (run="normal" which would be the default, run="startup" to run at startup, or run="exit" to launch on exit).
I am not sure it would be necessary to manage multi-values. But if so, I agree with you: it would be better to use a comma as separator.

-> In case one wishes to launch the same item on both startup and exit, he could still manage it with 2 items:
&lt;app name="myprogram" exe="exeloc" run="startup" /&gt;
&lt;app name="myprogram" exe="exeloc" run="exit" /&gt;

Other possible values would be when entering or exiting the screensaver (but would it be useful ?)

**Comment by obsidev** [comment]
Hi,

Commit aa2ee90307d4939762af27aba2e7efab6985c322 adds the support of events.
For the moment there is only "start" and "quit" ("exit").
I will add later "lock" and "unlock" and I have also to perform some tests in order to check that all is working right.

Adding twice the same application in the configuration to make it launch on different events looks a little bit weird because you will have twice the item in your menu configuration.
The current implementation allow to set several events for one single application.

Regards,
J

**Comment by ybilik** [comment]
Thanks a lot ! BYW, you are completely right about the duplicated items :)
(I have to install a Microsoft compiler in order to test your last changes...)

Regards,

Jan

**Comment by obsidev** [comment]
Hi,

I'll release soon a beta (or RC) binary.
If you want to compile PortAL yourself, you can use Visual Studio Community
https://www.visualstudio.com/en-us/products/free-developer-offers-vs.aspx
The "PortAL_vs2012.vcxproj" file is the project file for that version of VS (and it make me think that I should rename it)

Regards,
J
