### ISSUE TITLE
[PortAL] Problem with file pass in parameters

### ISSUE THREAD

**Issue by Shadeclan** [glatigny/guipro#2]
Hi, J.  Thought I'd try this out.

I'm having an issue with an APP tag - it's just launching a Word document:

`<app name="M204 Corp Bible" exe="C:\Program Files\Microsoft Office\Office15\WINWORD.exe" param="Y:\Documents\_Library_\Programming\Mainframe\Model 204\Corp M204 Bible.doc" />`

Is it the underscores in the _Library_ directory?

Woody

**Comment by obsidev** [comment]
Hi,

Because there is a space in the file path ; Word does not understand that there is not two parameters but that it is just one file.
So the best is to quote the filename (using `&quot;` because it's in a XML) or to open directly the file using the windows shell.

1 - `<app name="M204 Corp Bible" exe="C:\Program Files\Microsoft Office\Office15\WINWORD.exe" param="&quot;Y:\Documents\_Library_\Programming\Mainframe\Model 204\Corp M204 Bible.doc&quot;" />`

2 - `<app name="M204 Corp Bible" exe="Y:\Documents\_Library_\Programming\Mainframe\Model 204\Corp M204 Bible.doc" shell="true" />`

I wrote some documentation in the Wiki section ; there are also some examples (that I will improve with the time).

Regards,
J

**Comment by Shadeclan** [comment]
Thanks, J. 
Should I use this in all paths with spaces, including those in the **exe** parameter?

**Comment by obsidev** [comment]
PortAL handles spaces in the **exe** ; but **param** is passed directly to the launched program.
I will see to add an "auto quote" feature when **param** only contain a file path ; otherwise it will be difficult to detect what you might want to send to the program.

( You're welcome ! )

**Comment by Shadeclan** [comment]
That'll be nice - thanks!
