### ISSUE TITLE
Replacing HotKeyP with PortAL

### ISSUE THREAD

**Issue by Shadeclan** [glatigny/guipro#7]
J,
I'm nearly done with my PortAL reconfiguration and have completely replaced Tray Launcher - it's truly a thing of beauty!  Dude, you are an artist!

Also, with PortAL I've managed to replace nearly all the functionality of HotKeyP that I use by creating a second main group.  However, I'm having a little difficulty with functions like "Lock Computer", activating the current screen saver or turning off the monitor and minimizing the active window.  I can continue to use HotKeyP for this, either by using HotKeyP hot keys or by passing parameters to HotKeyP via PortAL.  However, I'd like to abandon HotKeyP and use PortAL exclusively.  Do you have a way to lock the computer / turn off the monitor / activate the screen saver / minimize the active window via PortAL?
You might also just take a look at HotKeyP for ideas to extend PortAL functionality.

**Comment by obsidev** [comment]
Hi,

Because you can execute program using the Windows shell, you can do all things that you can do in command line.
To lock the computer using command line

```
rundll32.exe user32.dll,LockWorkStation
```

So to lock the computer using portal

``` XML
<app name="Lock" exe="%system%/rundll32.exe" param="user32.dll,LockWorkStation" />
```

But personally, I'm using `Win+L`

About the screensaver, I'll recommend this:
http://stackoverflow.com/questions/1430108/how-to-turn-screensaver-on-windows-7-by-a-code-in-cmd

If you can perform an action using a command line, you should be able to do it in PortAL too !

For the window minimization (maximization, etc), it's one of the main goals of HulK.
Depending your configuration, it can minimize the active windows or the pointed window.

**Comment by Shadeclan** [comment]
J
Thanks.  I'll build a couple of batch files and add the code to my configuration.
I'll also take a look at HulK and see about utilizing it with my configuration.
Thanks for everything!
