### ISSUE TITLE
HulK Documentation

### ISSUE THREAD

**Issue by Shadeclan** [glatigny/guipro#8]
J,
Downloaded HulK.  Want to use it but there are no instructions.  Is there any documentation for configuring HulK?

**Comment by obsidev** [comment]
Hi,

I made a new HulK documentation page for the configuration.
https://github.com/obsidev/guipro/wiki/HulK-Configuration

Let me know if some points are still obscure to you.

Regards,

**Comment by Shadeclan** [comment]
Thanks, J.  Currently looking it over.

**Comment by Shadeclan** [comment]
OK ... well, here's something in the "KEYS" section.  You talk about the "key codes" but there is no explanation as to what that is.  You have a chart for the special keys but no information for other keys.  The reason I'm mentioning this is because the key under my escape key is the tilde (~) - can I put the tilde character in for the key value?  Can I put:

> key=~

?

The key code you speak of is not the ASCII code.  It is reminiscent of something I used to do in VB6.  If a key code chart exists on the internet, you may want to link to it.

Update: I can put the character there.  That was the last functionality of HotKeyP that I use.  I can now ditch it.  Thanks!

**Comment by obsidev** [comment]
Hi,

Key codes are codes for keys ; It will be hard for me to explain it because it's just how the system is working on low level.
https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731(v=vs.85).aspx
http://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes

HulK as PortAL will try to determine the keycode when it can ; so if you put a letter or a single character, it will try to figure it out.
Otherwise you can use the KeyBinding or put the keycode (thanks to the cambiaresearch link)
https://github.com/obsidev/guipro/wiki/PortAL-KeyBinding

Regards,
