### ISSUE TITLE
PortAL v1.4.7 not starting on Windows-XP 32-bit

### ISSUE THREAD

**Issue by derty2** [glatigny/guipro#9]
Hi developer, 
I cannot get this program to start on my Windows-XP 32-bit computer.
For a portable test run...I ran setup with "Portable" option to folder "C:\PortAL\" , then also copied four files "msvcp90.dll, msvcr90.dll, msvcp120.dll, msvcr120.dll" into app folder, then ran "PortAL.exe" (CRC32 = 9CAE2D5A)...

but I get this popup error message:

> > C:\PortAL\PortAL.exe is not a valid Win32 application.
> > I click 'OK' button and that is the end of that.

Do you have any debugging or troubleshooting tips because I have no idea why this program should not want to run; my operating system is healthy and runs everything I throw at it without problems.
Thanks.

---

My Analysis, using 'Dependency Walker (depends.exe)'

Run 'depends.exe' , then drag 'PortAL.exe' into 'Dependency Walker' window.......
'Dependency Walker' immediately pops up this error message:

> > Errors were detected when processing "C:\PortAL\PortAL.exe". See the log window for details.

Looking at the 'Log' window we see this BOLD RED TEXT:

> > Error: At least one required implicit or forwarded dependency was not found.
> > Warning: At least one delay-load dependency module was not found.
> > Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.
> > Warning: At least one module was corrupted or unrecognizable to Dependency Walker, but still appeared to be a Windows module.

Next, I go to menu 'Profile -> Start Profiling..." and click 'OK' (running without arguments).......

Looking at the 'Log' window we see nothing has loaded and this BOLD RED TEXT:

> > Failure starting the process. %1 is not a valid Win32 application (193).

Looking at the 'Modules List' window we see problems with the first four items:

> > [QuestionMark] EFSADU.DLL | Error opening file. The system cannot find the file specified (2).
> > [QuestionMark] MOBSYNC.DLL | Error opening file. The system cannot find the file specified (2).
> > [QuestionMark] MSJAVA.DLL | Error opening file. The system cannot find the file specified (2).
> > [Exclamation] PORTAL.EXE | Could not find the section that owns the Export Directory.

That's about it, hopefully my above analysis sheds something useful for the developer.
Cheers and good luck.

**Comment by obsidev** [comment]
Hi,

When I package PortAL, I use "upx" in order to reduce the binary size.
So I'm wondering if it could be the source of the issue (but it would be more than surprising).

Otherwise, I now compile PortAL using Visual Studio Community 2013 once I used Visual Studio 2008 some times ago.
So, the Visual Studio Redistribuable 2013 is required.
http://www.microsoft.com/en-US/download/details.aspx?id=40784

If you still have the issue, I will see to compile PortAL without UPX and compile PortAL with an older version of Visual Studio.

Regards,

**Comment by derty2** [comment]
**Try UPX-unpacking main application executable**

Loaded 'PortAL.exe' (CRC32=9CAE2D5A) into program 'PEiD v0.95 (with UPX handling plugins)'

PEiD main window reports:

```
[Entrypoint  : 000183E0] [EP Section  : UPX1       ]
[File Offset : 000067E0] [First Bytes : 60,BE,00,20]
[Linker Info : 12.0    ] [Subsystem   : Win32 GUI  ]
[UPX 0.89.6 - 1.02 / 1.05 - 2.90 -> Markus & Laszlo]
```

Ran plugin 'UPX FileInfo v0.1' ....this error message popped up:
`Error: Couldn't find jmp on oep!`

Ran plugin 'Unpacker for UPX' ....this error message popped up:
`Failed to run program`

This is the first time I have seen PEiD fail to unpack a UPX-packed EXE. The 'Unpacker for UPX' plugin has always worked for me on such binaries before this issue.

**Try adding system file 'efsadu.dll' to app folder**

Extract copy of 'efsadu.dll' (file version: 5.1.2600.5512) from Windows XP Setup CD ISO, using this command:
`expand EFSADU.DL_ -r`

Copy 'efsadu.dll' into app folder, then run 'PortAL.exe' .....it fails with error message:
`C:\PortAL\PortAL.exe is not a valid Win32 application.`

**Try adding Visual C++ 2013 modules to app folder**

This has already been tried; see my first post ("msvcp120.dll, msvcr120.dll").
[...]

Try one last thing....Copy all VC++ 2013 files installed at 'C:\Windows\system32' folder into the PortAL app folder
`mfc120.dll | mfc120chs.dll | mfc120cht.dll | mfc120deu.dll | mfc120enu.dll | mfc120esn.dll`
`mfc120fra.dll | mfc120ita.dll | mfc120jpn.dll | mfc120kor.dll | mfc120rus.dll | mfc120u.dll` 
`mfcm120.dll | mfcm120u.dll | msvcp120.dll | msvcr120.dll | vcomp120.dll`

Not Successful, I get same error message as before:
`C:\PortAL\PortAL.exe is not a valid Win32 application.`

That's about as far as I can analyze this developer. I have no more cards to play.
Good luck, and huge thanks for your prompt reply...respect ++++

_--derty2_

**Comment by obsidev** [comment]
Hi,

I found that Visual Studio 2013 have an option in order to compile with the Windows XP support.
https://msdn.microsoft.com/en-US/library/jj851139.aspx

What is the easier way to send you a new binary ?

Regards,

**Comment by derty2** [comment]
Hi,
If you want to quickly compile a binary for me to do a test run on my XP box, it would be nice.
Upload to this file hosting service: **[http://filebeam.com/](http://filebeam.com/)** and share the link here.
Filebeam is good because they give you stats about the number of times the file has been downloaded.
Thanks.

**Comment by obsidev** [comment]
Hi,

I upload one binary with XP compatibility - http://fbe.am/vRs

Regards,

**Comment by derty2** [comment]
I downloaded the binary you compiled with XP support...

**SUCCESS, IT WORKS!** ...after also copying 'msvcp120.dll' and 'msvcr120.dll' into app directory.

Dear developer, now that I have tested your program to see what it does, I would like to tell you what type of program I was really looking for...

I WAS NOT looking for just a system-tray menu/launcher; I was looking for an open-source replacement for the program **[PStart](http://www.pegtop.net/start/)** which is freeware without source code and the developer does not engage with discussion.

The interesting thing about PStart is that it could do what your program is doing but it also allowed you to have these options:
- Launch the menu as a Popup GUI window
- System tray icon could be enabled or disabled
- Various interesting customizable features in the popup GUI
- Create groupings and separators
- Custom subtext below each item
- Customizable exit behaviour when selecting or launching items

One interesting feature of your program which PStart did not have is the cascading submenu idea which is GREAT!!! It reminds me of the Windows XP classic start menu programs menu.

One thing I DID NOT LIKE with your program  (PortAL) is the mouse hover colors which are transparent light blue background with no text color change. It reminds me of Windows Vista/Seven which I HATE. I use Windows XP with classic start menu no themes no wallpaper and mouse hover colors are opaque dark blue background with white text.

Another brilliant little launcher program is **[PopSel, by Horst Schaeffer](http://www.horstmuc.de/wpop.htm)**. This program launches a popup menu which looks exactly like the right-click context menu; try it out and you will see what I mean.

Anyhow enough from me for now. Thankyou very much for everything, you look like a user-friendly developer with a great personality, I wish you all the best ++++++

---

P.S. -- There is an interesting little heirarchical two-pane notes organizer program written in C++ which has been abandoned by its developer but he gave away the source code too as open source. It is interesting because it also has a portable run mode, and it also launches any type of link including local files and folders so you can use it as an app launcher. It is like a document viewer and app launcher rolled into one. I like it a lot!!!!

It has some features missing which I would love to see..........If I support you with donation money, are you interested in building a new version of this program with the missing features and share it here on GitHub for everybody to use?

Would you like share emails with me?

**Comment by obsidev** [comment]
Hi,

Thanks for your feedback ; it's always interesting to have such kind of user opinion.
The new GUIPro release will contain x86 binaries compatible with Windows XP ; so you (or other XP users) won't have any issue anymore.

**1. design**
The blue design has been introduced four years ago, in PortAL 1.4.2 as you could see in the (some kind of) [old changelog](http://sourceforge.net/p/guipro/news/?source=navbar)
I did not remove the old design but I used compilation settings
[MENU_DRAW_V1 definition](https://github.com/obsidev/guipro/blob/master/PortAL/common.h#L34) so it's possible to create a binary with this old design.
If I remember right ; Firefox changed the design of his menus and I found it interesting ; so I made the new design.

It's right that today we are not in the same mood and we are going back to flat design but I didn't feel the need to change it because I use PortAL using a look a shortcuts or speed keys.
So I do not really look at the menus and how they are displayed ; but for sure I understand your point of view !

**2. GUI Window**
It was an idea that I got for PortAL ; idea which came from "Window Maker".
But I made some tests some years ago and I didn't find something which feet to my expectations ; the "menu" interface was working good and finally, I didn't need anymore to always have a persistent window because I have good shortcut to make it re-appear fast.

You mentioned in your PS an another open-source project but without a name or link ; what is this program exactly ?

About the points:
- Create groupings and separators
- Customizable exit behavior when selecting or launching items

I'm not sure I fully understand what you mean. For the groups and separators, PortAL have some, so I guess that you're talking about something different.

**3. Development**
When I started GUIPro 8 years ago it was software for myself with the goal of having very light tools (tiny memory footprint, etc).
I have other software which are more "products" but GUIPro stayed as an hobby. They are the tools I needed to (and some other need to ; it's mostly why they are/were bad documented special features).

For sure I want to continue improving it and I'm also open to external improvements (Pull Request as called here) ; it's just I don't want to think about that project as an obligation or a potential source of money, it's purely passion and something that I can improve when I have the time to (and when users give improvement ideas).

I did not made "advertisement" or "indexation" of GUIPro, I know that there are not a lot of users (but they are good one, I received great emails) and that not having an editor for the configuration is a big lack for most people.

Kind regards,
J

**Comment by derty2** [comment]
Hi "J"
I send you here an initial private email reply to see if you receive it....

I would like to upload my copy of the program (with C++ sourcecode and
docs) which I mentioned in the "P.S." at GitHub. This way you can
download and run it for a quick interactive demo.
Also, I will include some notes for you to read explaining more.

Are you OK with this?

P.S. -- Do you have a private contact email external from github?

Cheers
--derty2

**Comment by obsidev** [comment]
Hi,

My contact email is public on my GitHub profile https://github.com/obsidev
It will be the easiest way :)

Best regards,
J
